### ISSUE TITLE
Cannot install serialport on Raspbian, raspberry pi

### ISSUE THREAD

**Issue by joe4465** [serialport/node-serialport#133]
Hi,

I'm having issues installing serial port. My versions are:

pi@raspberrypi ~/node $ node -v
v0.8.16
pi@raspberrypi ~/node $ npm -v
1.1.69
I have installed gyp globally using "sudo npm install -g node-gyp". I can install other packages fine. I have installed node build-essential, nodejs-dev libssl etc.

When i try and install serialport i get this,

pi@raspberrypi ~/node $ sudo npm install serialport
npm http GET https://registry.npmjs.org/serialport
npm http 304 https://registry.npmjs.org/serialport
npm http GET https://registry.npmjs.org/bindings/0.3.0
npm http GET https://registry.npmjs.org/async/0.1.18
npm http GET https://registry.npmjs.org/sf/0.1.3
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/node-gyp/0.6.2
npm http 304 https://registry.npmjs.org/node-gyp/0.6.2
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/async/0.1.18
npm http 304 https://registry.npmjs.org/bindings/0.3.0
npm http 304 https://registry.npmjs.org/sf/0.1.3
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/npmlog
npm http GET https://registry.npmjs.org/osenv
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/npmlog
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/osenv
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/ansi
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/block-stream
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/ansi
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/block-stream

> serialport@1.0.8 install /home/pi/node/node_modules/serialport
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.8.16"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/node/node_modules/serialport/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: ENOSPC, mkdir '/home/pi/node/node_modules/serialport/.node-gyp'
gyp ERR! System Linux 3.6.11+
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/node/node_modules/serialport
gyp ERR! node -v v0.8.16
gyp ERR! node-gyp -v v0.8.4
gyp ERR! not ok
npm ERR! serialport@1.0.8 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the serialport@1.0.8 install script.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.6.11+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "serialport"
npm ERR! cwd /home/pi/node
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.69
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/node/npm-debug.log
npm ERR! not ok code 0

This directory "gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.8.16"" dosn't seem to exist.

Any help would be much appreciated, I've been trying to get this working for days.

Thanks
Joe

**Comment by eliasruizhz** [comment]
@joe4465 
pi@raspberrypi: > sudo passwd root
change password: raspberry
confirm: raspberry
pi@raspberrypi: > exit
mac: > ssh root@ip.ip.ip.ip
password: raspberry
root@raspberrypi: > cd /home/pi
root@raspberrypi: > npm install serialport@1.6.1
Success!!
