### ISSUE TITLE
No data after waking up from hibernation/sleep/standby

### ISSUE THREAD

**Issue by adrai** [serialport/node-serialport#157]
First scenario:
1. connect to a serialport
2. write some data    --> data event is emitted 
3. let system go to sleep
4. let system wake up
5. write some data    --> data event is not (never) emitted

to work again with the device I have to unplug it and retry...

Second scenario:
1. connect to a serialport
2. write some data    --> and directly go to sleep
3. let system go to sleep
4. let system wake up
5. --> data event is not (never) emitted

@voodootikigod any ideas?

**Comment by roccomuso** [comment]
I'm having the same issue with arduino.
