### ISSUE TITLE
RFID reader won't response

### ISSUE THREAD

**Issue by ricefish888** [serialport/node-serialport#1798]
Here is my code，RFID reader won't response：

var SerialPort = require('serialport')
//Opening a Port
var serialPort = new SerialPort('COM3', {
    baudRate : 57600,
    autoOpen:false
})

serialPort.open(function (err) {
    console.log('IsOpen:',serialPort.isOpen)
    console.log('err:',err)
})

serialPort.on('data',function (data) {
    console.log('data received: '+data)
})

serialPort.on('error',function (error) {
    console.log('error: '+error)
})

SerialPort.list(function (error, ports) {
    ports.forEach(function(port) {
      //  console.log(port.comName);
      //  console.log(port.pnpId);
      //  console.log(port.manufacturer);
    });
})

**Comment by callen5914** [comment]
Just curious, which reader are you using? I am building a similar project with the sparkfun rfid reader.
