### ISSUE TITLE
No data are being passed into terminal 

### ISSUE THREAD

**Issue by dhiren999** [serialport/node-serialport#1801]
### Summary of Problem
Hi,
I have digital scale connected to PC via RS232 serial port. 
When I run the application via "node app.js" all I can see is "port open, Data Rate: 9600" 
and nothing else. 

I know the scale and connection works because I have another application developed on C# which gets 
weight data from the same scale without problem.

Please help me to fix the issue.

Thank you.
(Please answer all 3)

- What are you trying to do? Get data from digital scale to PC via RS232 port
- What happens? No data are being pass
- What should have happened? Should transfer the data in terminal

### Code to Reproduce the Issue

```js
var SerialPort = require('serialport');// include the library
const Delimiter = require('@serialport/parser-delimiter')
// get port name from the command line:
var portName = process.argv[2];

var myPort = new SerialPort(portName, 9600);
var parser = myPort.pipe(new Delimiter({ delimiter: '\n'})) // make a new parser to read ASCII lines
myPort.pipe(parser); // pipe the serial stream to the parser

myPort.on('open', showPortOpen);
parser.on('data', readSerialData);
myPort.on('close', showPortClose);
myPort.on('error', showError);

function showPortOpen() {
    console.log('port open. Data rate: ' + myPort.baudRate);
 }
  
 function readSerialData(data) {
    console.log(data);
 }
  
 function showPortClose() {
    console.log('port closed.');
 }
  
 function showError(error) {
    console.log('Serial port error: ' + error);
 }
// Code
```

### Versions, Operating System and Hardware

- SerialPort@? 7.1.4
- Node.js v? 10.13.0
- Windows? Linux? Mac? Windows 10
- Hardware and chipset? (Prolific/FTDI/Other) Sartorius digital scale connected via RS232 port.

**Comment by mike-io** [comment]
Are you still having problems with this? 

I tried this out, and it works fine, just remove the line `myPort.pipe(parser); // pipe the serial stream to the parser` - this doesn't really make sense, and the preceding line sets up the parser on it's own anyway.

Cheers!
