### ISSUE TITLE
Electron - error on npm start

### ISSUE THREAD

**Issue by zytra** [serialport/node-serialport#1811]
Hi,
I was finally able to get serialport to install/work with electron; running node.js v10.15.1, electron 4.0.2 and serialport 7.1.3 (tried 7.1.4 with the same results), however I am getting the following error message (see below) as soon as I start adding the basic sample code from the doc.

here's what my package.json looks like:

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "author": "l",
  "license": "MIT",
  "dependencies": {
    "electron": "^4.0.2",
    "serialport": "^7.1.3"
  }
}
```

and here's what my main.js looks like:
```
const electron = require('electron');
const url = require('url');
const path = require('path');

const {app, BrowserWindow} = electron;

let mainWindow;

//Listen for the app to be ready
app.on('ready', function(){
    //Create new window
    mainWindow = new BrowserWindow({});
    //Load html into window
    mainWindow.loadURL(url.format({
        pathname: path.join(__dirname, 'mainWindow.html'),
        protocol:'file:',
        slashes: true
    }));
});

const SerialPort = require('serialport')
const port = new SerialPort('COM3', {
  baudRate: 9600
});

// Read data that is available but keep the stream in "paused mode"
port.on('readable', function () {
  console.log('Data:', port.read())
});

// Switches the port into "flowing mode"
port.on('data', function (data) {
  console.log('Data:', data)
});
```

this literally is the basic usage from this page: https://serialport.io/docs/en/guide-usage
with just a little bit of basic JS for electron

I had troubles getting serialport to work, because of NODE version issues between NODE.js, electron and serialport and finally found a combination that would actually let me run my npm start command..

again, this piece of code works if I remove the serialport stuff from my script.

> 
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'start' ]
> 2 info using npm@6.4.1
> 3 info using node@v10.15.1
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle test@1.0.0~prestart: test@1.0.0
> 6 info lifecycle test@1.0.0~start: test@1.0.0
> 7 verbose lifecycle test@1.0.0~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle test@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\irisneuro\node_modules\.bin;C:\Users\Stephen\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Stephen\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft MPI\Bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files (x86)\Elmer 8.2-Release\bin;C:\Program Files\MPICH2\bin;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Users\Stephen\AppData\Local\Microsoft\WindowsApps;C:\Dev-Cpp\mingw32\bin;C:\Users\Stephen\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Stephen\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
> 9 verbose lifecycle irisneuro@1.0.0~start: CWD: D:\test
> 10 silly lifecycle irisneuro@1.0.0~start: Args: [ '/d /s /c', 'electron .' ]
> 11 silly lifecycle irisneuro@1.0.0~start: Returned: code: 3228369023  signal: null
> 12 info lifecycle irisneuro@1.0.0~start: Failed to exec start script
> 13 verbose stack Error: irisneuro@1.0.0 start: `electron .`
> 13 verbose stack Exit status 3228369023
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
> 13 verbose stack     at EventEmitter.emit (events.js:189:13)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:189:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:970:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 14 verbose pkgid test@1.0.0
> 15 verbose cwd D:\test
> 16 verbose Windows_NT 10.0.17134
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> 18 verbose node v10.15.1
> 19 verbose npm  v6.4.1
> 20 error code ELIFECYCLE
> 21 error errno 3228369023
> 22 error test@1.0.0 start: `electron .`
> 22 error Exit status 3228369023
> 23 error Failed at the test@1.0.0 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 3228369023, true ]
>

**Comment by chiamtc** [comment]
I dont see `electron-rebuild` in your package.json.
Have you done step under "Electron", https://serialport.io/docs/en/guide-installation
```
npm install --save-dev electron-rebuild
Add electron-rebuild to your project's package.json's install hook
Run npm install
```
Best of luck.
