### ISSUE TITLE
what is the solution for this error ? emerginfTexhnologyAdvisors 

### ISSUE THREAD

**Issue by mohdmahdi** [serialport/node-serialport#1989]
I'm trying to connect my Arduino with (electron js) app and I'm using this example : 
https://github.com/sofroniewn/electron-johnny-five-examples

when I followed the instructions I found that there is an error related to the serial port ( find the attached capture ) , could you please help me ! 
![Screen Shot 2019-11-11 at 12 55 18 AM](https://user-images.githubusercontent.com/42738688/68551894-5cc47700-0422-11ea-853f-7f8c9185a350.png)

**Comment by frank-dspeed** [comment]
thats not a error at all you can close this issue it tells you only that there was no binaray created for your operating system so he creates one. thats it.
