### ISSUE TITLE
over 230400 bps on osx

### ISSUE THREAD

**Issue by takegata** [serialport/node-serialport#2034]
hi, i'm using node_modules/serialport in an electron app.
I'd like to set it's baudrate to 921600.
on windows it's fine but on osx it's not.

i found following in serialport_unix.cpp

```
case 230400: return B230400;
#if defined(__linux__)
case 460800: return B460800;
```

isn't it related to this problem?
thank you.

Seiji Takegata
takegata@veltec.co.jp

**Comment by Azq2** [comment]
https://github.com/serialport/bindings-cpp/pull/186
