### ISSUE TITLE
Implement read timeout using Promise.race

### ISSUE THREAD

**Issue by JBtje** [serialport/node-serialport#2050]
### Summary
If you use the serialport/bindings to read/write directly (no wrapper), you might want to implement a read timeout to prevent your code from hanging.

`Promise.race` will complete once any of the Promises completes. You can provide two Promises; one is the returned Promise of `binding.read` whilst the other Promise is a timeout.

The timeout will wait (in this example) 2.5 seconds prior to triggering `reject`. Thus, the read Promise has 2.5 seconds to complete. The below example reads a total of 10.000 Bytes. The read promise will complete (in my case) after reading 64 Bytes. Thus increasing the `ofs` and staying in the loop until all bytes are read, or 2.5 seconds have expired after the last succesful read.

### Example Code
```js
const Binding     = require( '@serialport/bindings' );
const comName     = 'COM1';
const openOptions = {
    baudRate: 115200,
    dataBits: 8,
    stopBits: 1,
    parity:   'none',
};

const binding = new Binding();

(async() => {
    await binding.open( comName, openOptions );
    await binding.write( Buffer.from( 'AA000002', 'hex' ) );

    const L   = 10000;
    const pkg = Buffer.alloc( L );
    let ofs   = 0;

    while( ofs < numBytes ) {
        await Promise.race( [
            binding.read( pkg, ofs, numBytes - ofs ),
            new Promise( ( resolve, reject ) => setTimeout( reject, 2500 ) ),
        ] ).then(
            ( {bytesRead, buffer} ) => ofs += bytesRead,
            err => this.SerialPort.close(),
        ).catch( () => this.SerialPort.close() );
    }
    await binding.close();
})();
```

### Versions, Operating System and Hardware

- @serialport/bindings: 8.0.7
- SerialPort@8.0.7

**Comment by fernandomantoan** [comment]
Hello, I was searching this repo about using async/await instead of callbacks and found your issue. Are there any disadvantages of not using the "wrapper"? I was wondering why the docs use callbacks instead of Promises, with Promises the code is more readable and predictable. Where did you find info about using async/await in node-serialport?
