### ISSUE TITLE
prebuild-install bindings-v8.0.7 get 404 result

### ISSUE THREAD

**Issue by JesseWeb** [serialport/node-serialport#2061]
### Summary of Problem

(Please answer all 3)

- What are you trying to do?
trying to build win64 app in macOS
- What happens?

- What should have happened?
get this error
```
 prebuild-install http 404 https://github.com/serialport/node-serialport/releases/download/@serialport/bindings@8.0.7/bindings-v8.0.7-electron-v76-linux-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=8.2.0 runtime=electron arch=x64 libc= platform=linux)
```

### Versions, Operating System and Hardware

- SerialPort@8.0.7
- Node.js v10.15.3
- electron@8.2.0
- Mac

**Comment by mkurczewski** [comment]
It's a duplicate of #2031 - still unresolved :(

**Comment by JesseWeb** [comment]
any progression in this issue?

**Comment by mkurczewski** [comment]
@JesseWeb look at https://github.com/serialport/node-serialport/issues/2031. The issue is resolved now.

**Comment by JesseWeb** [comment]
> @JesseWeb look at https://github.com/serialport/node-serialport/issues/2031. The issue is resolved now.

Glad to hear that!
