### ISSUE TITLE
TypeError: Class constructor ReadLineParser cannot be invoked without 'new'

### ISSUE THREAD

**Issue by felipeguerrero87** [serialport/node-serialport#2062]
### Summary of Problem

I have problems trying to read the serial port from arduino, I have the problem that tells me
Class constructor ReadLineParser cannot be invoked without 'new'

I leave my code to reproduce the error

some help?

(Please answer all 3)

- What are you trying to do?
reading data from arduino
- What happens?
I have this error when executing my file
 Class constructor ReadLineParser cannot be invoked without 'new'
- What should have happened?
read from the serial port

### Code to Reproduce the Issue

```js
const serialport = new SerialPort(path)

// Code
var serialport = require('serialport');
var SerialPort = serialport.SerialPort;
var portName = process.argv[2];


var myPort = new SerialPort(portName,{
    baudRate: 9600,
    parser: serialport.parsers.Readline("\r\n")
})

myPort.on('open', onOpen);
myPort.on('data', onData);


function onOpen(){
    console.log('Open connection');
}

function onData(){
    console.log('on Data: '+data)
}
```

### Versions, Operating System and Hardware

- SerialPort@?
- Node.js v?
- Windows? Linux? Mac?
- Hardware and chipset? (Prolific/FTDI/Other)

**Comment by NunMimYa** [comment]
Hola, 

después de investigar un poco en otros foros (mismo problema de mi lado), parece que solo hubo algunos errores...
Espero que esto ayude aunque el problema se remonta a más de un año.

Cordialmente.
