### ISSUE TITLE
DLL errror on NW.JS

### ISSUE THREAD

**Issue by JurijTSL** [serialport/node-serialport#2112]
### Summary of Problem

- What are you trying to do? Read serial data sent from Arduino in NW.JS app
- What happens?
It throws an error and nothing happens:
![image](https://user-images.githubusercontent.com/30342756/88431776-4c5efb80-cdfb-11ea-9aed-5704c74ff90f.png)

- What should have happened? Read serial data.

### Code to Reproduce the Issue

```js
const SerialPort = require('serialport');
const Readline = require('@serialport/parser-readline');
const port = new SerialPort('COM3', { baudRate: 9600 });
const parser = port.pipe(new Readline({ delimiter: '\n' }));

// Read the port data
port.on("open", () => {
    console.log('serial port open');
});
parser.on('data', data =>{
    console.log('got word from arduino:', data);
});
```

### Versions, Operating System and Hardware

- SerialPort@? COM3
- Node.js v? v12.13.1
- NW.JS v? v0.47.0-SDK
- Windows? Linux? Mac? Windows 10.
- Hardware and chipset? (Prolific/FTDI/Other) Arduino

**Comment by Kalmon** [comment]
I have the same problem ....

**Comment by LucianoPerezMontalvan** [comment]
Same problem here, i think is something bout prebuild, but can't find a solution
