### ISSUE TITLE
Serial port stops receiving data after a while

### ISSUE THREAD

**Issue by rohitrai1** [serialport/node-serialport#2113]
I am fetching the sensor data from 'Arduino nano' using the byte length parser. The frames are accurate, however, I stop receiving the frames after a few minutes. I have the same piece of code in Matlab and it works perfectly fine, meaning that there is no problem at the device end. Something's wrong at Nodejs side. I want my node server to continuously receive the data

### Code to Reproduce the Issue

var portName = "/dev/ttyACM1";
const myPort = new Serialport(portName, {
  baudRate: 115200,
  xon: true,
  xoff: true
});

const Delimiter = require("@serialport/parser-delimiter");
const parser1 = myPort.pipe(new Delimiter({ delimiter: "\n" }));

parser1.on("data", data => {
}
// Code
```

### Versions, Operating System and Hardware

- SerialPort version - 9.x.x
- Node.js v - v10.15.3
- Linux - Ubuntu 16.04
- Hardware and chipset - Arduino Nano Every

**Comment by carloscastellanos** [comment]
Opening this up again. Having the same problem. Stops receiving data after about 30 seconds. All I am doing is reading data from a single analog input of an Arduino.

macOS 12.6.2
Node.js 18.15.0
serialport 10.5.0

Node.js code:

`const { SerialPort, ReadlineParser } = require("serialport"); // Import the serialport library

let portName = process.argv[2]; // get the port name from the command line

// if they didn't give a port name, tell them so, then quit:
if (!portName) {
  giveInstructions();
}

const myPort = new SerialPort({ path: portName, baudRate: 9600 }); // open the port
const parser = new ReadlineParser(); // make a new parser to read ASCII lines
myPort.pipe(parser); // pipe the serial stream to the parser

// ==== these are the definitions for the serial events: ===== //
myPort.on("open", () => {
  console.log("Serial port opened");
}); // called when the serial port opens

myPort.on("data", (data) => {
  //const val = parseInt(data);
  console.log(data.toString());
}); // Read incoming serial data & print the value to the console

myPort.on("close", () => {
  console.log("port closed.");
}); // called when the serial port closes

myPort.on("error", (err) => {
  console.log(err);
}); // called when there's an error with the serial port

function giveInstructions() {
  //console.log('you did not give a port name');
  console.log("To run this properly, type \n");
  console.log("node serial_input.js \n");
  //console.log('run the listPorts script to get a list of ports.\n');
  process.exit(0);
}
`
Arduino code

`
// the setup routine runs once when you press reset:
void setup() {
  // initialize serial communication at 9600 bits per second:
  Serial.begin(9600);
}

// the loop routine runs over and over again forever:
void loop() {
  // read the input on analog pin 0:
  int sensorValue = analogRead(A0);
  // print out the value you read:
  Serial.print("A0");
  Serial.println(sensorValue);
  delay(10);  // delay in between reads for stability
}
`
