### ISSUE TITLE
Read data from weighing machine via USB to serial interface

### ISSUE THREAD

**Issue by fdbatista** [serialport/node-serialport#2146]
### What are you trying to do?
I want to read data from a digital weighing machine connected via USB to port COM4 on my Windows 10 computer.
To do so, I need to send the character 'P' to the weighing machine and then I need to read the response.
I was also trying to send the data as hex (0x50)  but it throws an error.

### What happens?
Nothing. The port gets opened, but it looks like there is no communication with it. The `results` callback variable is  `undefined`.

### What should have happened?
I was expecting to be able to send the character 'P' to the COM port and get a weight as a result.

### Code to Reproduce the Issue

```js
const SerialPort = require('serialport')

const port = new SerialPort('COM4', {
    baudRate: 115200,
    autoOpen: false
});

port.open(function (err) {
    if (err) {
        console.log('Error opening port: ', err.message);
    }
});

port.on("open", function () {
    console.log("open");
    
    port.on("data", function(data) {
      console.log("data received: " + data);
    });  

    port.write("P\n", function(results) {
      console.log("results: " + results);
    });
    
    if (port.isOpen) {
        port.close();
    }

  });
```

### Versions, Operating System and Hardware

- SerialPort@9.0.1
- Node.js v14.12.0
- Windows 10 Home Edition
- Hardware and chipset: Torrey PCR Commercial Weighing Machine

**Comment by jsftsylvain** [comment]
I am having an issue where I cannot read data from the serialport when I declare it as a variable. Try declaring it as a constant.
[my issue](https://github.com/serialport/node-serialport/issues/2136)

**Comment by fdbatista** [comment]
> I am having an issue where I cannot read data from the serialport when I declare it as a variable. Try declaring it as a constant.
> [my issue](https://github.com/serialport/node-serialport/issues/2136)

Thanks, @jsftsylvain I will give it a try and let you know what happens. Cheers!

**Comment by fdbatista** [comment]
> I am having an issue where I cannot read data from the serialport when I declare it as a variable. Try declaring it as a constant.
> [my issue](https://github.com/serialport/node-serialport/issues/2136)

Him @jsftsylvain You were right, declaring it as a `const` did the job.
I managed to solve this issue by subscribing to the port events outside of the scope of the `open` listener.

And I ended up creating my own wrapper for this job.
You can check it out here:

https://github.com/fdbatista/nodejs-torrey-weighing-machine

It is still work in progress, but any suggestions are welcome 👍 

Thanks.
