### ISSUE TITLE
Checking physical connection (Carrier detect, DСD pin voltage).

### ISSUE THREAD

**Issue by fend25** [serialport/node-serialport#215]
How to check that cable is physically connected? As I know, I should check value (0 or 1) on the DCD pin.
For example, there is SerialPort.CDHolding property (bool flag) in C#.
http://msdn.microsoft.com/en-us/library/system.io.ports.serialport.cdholding.aspx

I really liked this library, but I can't find any work with DCD in it.

**Comment by jimmyacademy** [comment]
@fend25 I also want to check the Carrier detect value for serial port but I did not find any functions in the library to check this value. I might need to add a wrapper function to check the CD value like you did. Could you please elaborate more about how you modified the serialport.cpp file? I'd really appreciate your help.
