### ISSUE TITLE
Fails to open named pipe on Linux

### ISSUE THREAD

**Issue by lcrocker** [serialport/node-serialport#2154]
Linux programs that talk to serial ports universally support talking to any TTY device, including named pipes. This is simple because the same OS calls are used for both. The only difference is that real serial ports also support some Ioctls for changing baud rate and such. Programs that talk to TTY devices simply don't call those Ioctls, or else don't quit when they fail.

Opening a named pipe with node-serialport results in:

Error: Inappropriate ioctl for device setting custom baud rate of 9600

(This is with the options argument set to {}. If it includes an actual baudRate, that number will appear in the error). This could be trivially fixed by either tolerating the error, or else having a "don't set baudrate" option.

**Comment by Igorek536** [comment]
Confirm that bug. Any ways to fix it?
