### ISSUE TITLE
 How to send password required for login

### ISSUE THREAD

**Issue by Vn-ChemGio** [serialport/node-serialport#2189]
Hey guy!
I'm have being creat nodeJs app for monitor and controll some old device
But I have a problem
When using Hyper Terminal to connect device, after call connect, My device will require a Password, and I have to input device's password to verify (Password store in device)
So, How can I send /write .... password to device when create a instance SerialPort or open connect ....
Thank for help !

Here is my example use case in Hyper terminal

![102068401-3d301880-3db1-11eb-97da-38cc02653a51](https://user-images.githubusercontent.com/25608423/102102573-8f7b4300-3e5e-11eb-8b7e-0c03b166b987.png)

**Comment by GazHank** [comment]
Hi @Vn-ChemGio are you still facing issues with this?  I'd assume you just need to open the port and call a read or write operations, but perhaps I'm missing something

**Comment by Vn-ChemGio** [comment]
I were fixing this issue !
by send "enter" symbol to device after connected
Because this device always stored last my input after disconected
