### ISSUE TITLE
Parity Error Under Linux

### ISSUE THREAD

**Issue by ergousha** [serialport/node-serialport#219]
I am using this simple code to send a byte through serialport. And I watch the result with a logic analyser hardware. As it seems below, same code produces expected correct result under Windows, but it gives a parity error under Linux (Raspberry Pi)
I intended to use 'even' parity which is apparently the problem. Windows version interprets correct, but Linux version fails and using default value 'none'. 
When I use parity default value 'none' I got same result for both Windows and Linux.

var sp = new SerialPort('/dev/ttyAMA0', {
    baudRate: 19200,
    dataBits: 8,
    parity: 'even',
    stopBits: 1,
    flowControl: false
});

var serialBuffer = new Buffer([0x01]);
sp.write(serialBuffer);

![untitled-4](https://f.cloud.github.com/assets/2912014/1172716/4fc70a14-2129-11e3-99a7-2f1a9f4228f9.png)

**Comment by PiyushRamuka** [comment]
@ergousha - I am having similar issue. Made the changes in issue #413. Do i need to rebuild the .cpp file? If so, how can I do it?
