### ISSUE TITLE
How to use this with angular?

### ISSUE THREAD

**Issue by ThakkarKhushbu** [serialport/node-serialport#2192]
How to use this with angular 6+?

**Comment by GazHank** [comment]
Hi @ThakkarKhushbu 

did you have any luck resolving this issue?  I see there have been a number of [previous closed issues related to the use of angular](https://github.com/serialport/node-serialport/issues?q=is%3Aissue+angular+), so I'm not sure if they would help, or if looking at an existing project which uses angular might help e.g. https://github.com/yu4321/Angular-Electron-SerialPort_ThermalPrinterExample
