### ISSUE TITLE
[9.x] Undefined symbol from bindings.node and Electron 9

### ISSUE THREAD

**Issue by fugisakimatheus** [serialport/node-serialport#2216]
When start Electron this error bellow appear

```
 /home/mzdev-02/development/grandchef-desktop/node_modules/electron/dist/electron --inspect=44095 /home/mzdev-02/development/grandchef-desktop/dist/main/main.js: symbol lookup error: /home/mzdev-02/development/grandchef-desktop/node_modules/@serialport/bindings/build/Release/bindings.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
```

**Comment by GazHank** [comment]
Hi @fugisakimatheus if you are still facing issues would you be able to share a little information about the platform you are using?

### Versions, Operating System and Hardware

- SerialPort@?
- Node.js v?
- Electron (if applicable) v?
- Prebuild? Build from Source? 
- Operating system and version: Windows? Linux? Mac?
- Architecture: i32/x86? x64? ARM?
