### ISSUE TITLE
removeListener not woking

### ISSUE THREAD

**Issue by marmoure** [serialport/node-serialport#2242]
```javascript
const port = new SerialPort("COM");
parser.on("data",onPortData);

function onPortData(chunk: string) {
    if(conditionMet) {
        port.removeListener("data",onPortData);
    }
}
```
i m using removeAllListeners for now and its working fine

- SerialPort@9.0.7
- Node.js v15.13.0
- Windows
- GSM modem

**Comment by GazHank** [comment]
Hi @marmoure is it just a typo that line two refers to parser rather than port?
