### ISSUE TITLE
How to open another one port when the original one does not exist

### ISSUE THREAD

**Issue by chungkai1029** [serialport/node-serialport#2245]
I'm trying to connect to an USB port that connect to a HMI to read data.
When I try to connect, the error shows "Error= Error: No such file or directory, cannot open /dev/ttyUSB0".
So I have to check list of /dev by using command and correct to another port like "/dev/ttyUSB1". 
I would like to ask whether there is a better way to check the port exist inside my program by if...else... ? 

Here is my code for this issue:

```js
var serialPort = require("serialport");
var portOfHMI = new serialPort("/dev/ttyUSB0", {
    baudRate: 9600,
    dataBits: 8,
    parity: "none",
    stopBits: 1
});
portOfHMI.on("error", function (err) {
    console.log("Error= " + err.message);
 });
portOfHMI.on("data", function (data) {
    console.log("Data= " + data);
 });
```

```bash
Error= Error: No such file or directory, cannot open /dev/ttyUSB0
```

And, my version list is over here:

- SerialPort@9.0.7
- Node.js v14.16.0
- Debian 9 OS
- Beaglebone like Hardware

**Comment by GazHank** [comment]
Hi @chungkai1029,

I think you might want to try searching for and selecting the device based on the vendor and product id of the device you are trying to communicate with.

For example we use something like:

 ```
 async find(...devices) {
    let portList = await SerialPort.list();

    let found_devices = [];

    this.debugLog("focus.find: portList:", portList, "devices:", devices);

    for (let port of portList) {
      for (let device of devices) {
        if (
          parseInt("0x" + port.productId) == device.usb.productId &&
          parseInt("0x" + port.vendorId) == device.usb.vendorId
        ) {
          let newPort = Object.assign({}, port);
          newPort.device = device;
          found_devices.push(newPort);
        }
      }
    }

    this.debugLog("focus.find: found_devices:", found_devices);

    return found_devices;
  }
```

We have a few supported devices so store these in the 'devices' with appropriate device.usb.productId and device.usb.vendorId values.  If you are targetting just a single device you could simplify the code a little.

By seaching based on the IDs we only try to interact with supported devices and don't risk either trying to connect to a missing device or sending messages to someone else's kit.  

This should address your issue above, and should also help make the code work on different operating systems which use different port names.

hope this helps

Gaz

**Comment by GazHank** [comment]
Hi @chungkai1029 are you still facing any issues?  or is there any extra info that may be helpful?

**Comment by chungkai1029** [comment]
Hi @GazHank , it's really helpful for me to use.
Thanks for your helping.
