### ISSUE TITLE
Parity "even" does not work

### ISSUE THREAD

**Issue by jmades** [serialport/node-serialport#2284]
When I change the parity from "none" to "even" the port behaves eactly like parity "none".

Test performed on a Raspberry Pi 3 with RS485 shield as sender and a PC with RS485-2-USB converter on running docklight.

**Comment by GazHank** [comment]
Hi @jmades,

are you able to share a little more information about your environment, and perhaps a sample of (or link to) the code that you are trying to use?

- SerialPort v?
- Node.js v?
- Electron (if applicable) v?
- Prebuild? Build from Source?

**Comment by jmades** [comment]
> 
> 
> Hi @jmades,
> 
> are you able to share a little more information about your environment, and perhaps a sample of (or link to) the code that you are trying to use?
> 
>     * SerialPort v?
8.0.7
> 
>     * Node.js v?
12.22.1
> 
>     * Electron (if applicable) v?
not used
> 

>     * Prebuild? Build from Source?
Build from source

`import SerialPort = require('serialport');

let message: string = 'Hello World';
console.log(message);
test_connect_config();

function test_connect_config() {

    console.log("Connecting...");

    const port = new SerialPort('/dev/ttyS0', {
            baudRate: 9600,
            dataBits: 8,
            stopBits: 1,
            parity: 'even'
        },
        error => {
            if (error !== null) {
                console.error(error);
            }
        }
    );

    port.write('test', (error?: Error | null) => {});
}
`

**Comment by GazHank** [comment]
hi @jmades is it possible that this is related to https://github.com/serialport/node-serialport/issues/1413? If so it looks like the thread to address this may be found at https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=198999

**Comment by jmades** [comment]
Thanks, this solved my problem.
