### ISSUE TITLE
When I use Serialport.list(), it gives me nothing but an empty array. What is wrong with it ?

### ISSUE THREAD

**Issue by ramazanncicek** [serialport/node-serialport#2326]
Actually my title explaines it. I installed 'npm install serialport' and when I use the code below,which I have taken from here as well, gives me nothing. console.log(ports) part gives me an empty array only.

`const SerialPort = require('serialport');
// Promise approach
SerialPort.list().then(ports => {
    console.log(ports);
  ports.forEach(function(port) {
  // Manipulate here.
  });
});`
Besides, when I check from resources to see ports in Device Manager, there is no 'PORTS' tab in my Device Manager. Can these be linked by any chance ?

**Comment by tniezurawski** [comment]
@ramazanncicek I know it was long time ago but do you remember what you meant by using `node-hid`? Both `node-hid` or `usb` will give you a list of devices but how do you know anything about their COM ports? _(I have a USB thermal printer exposing virtual COM)_

I'm facing the problem where `await SerialPort.list()` returns an empty array, but if I connect to a port I know exists (`COM3` in my case), it works like a charm. So definitely, there is a port ready to be used, but somehow it's not listed 🤷‍♂
