### ISSUE TITLE
SerialPort.list() Win10 "Uncaught (in promise) hole" Error

### ISSUE THREAD

**Issue by msamgar** [serialport/node-serialport#2328]
Hello there,
"electron": "^12.0.9",
"serialport": "^9.2.4"
operating system: Windows 10

I am using the library.

const serialport = require('serialport')

async function listSerialPorts() {
    var port_list = Array();
    await serialport.list().then((ports, err) => {
        if(err) {
            document.getElementById('error').textContent = err.message
            return
        } else {
            document.getElementById('error').textContent = "";
        }
        // console.log('ports', ports);
        port_list = ports;
        if (ports.length === 0) {
            document.getElementById('error').textContent = i18n.__("l_not_found_port");
        } else {
            // Clear ComboBox
            $('#serial_port').empty();
        }
    })

    for(var i=0; i<port_list.length; i++) {
        // console.log(port_list[i].path);
        var opt = document.createElement('option');
        opt.value = port_list[i].path;
        opt.innerHTML = port_list[i].path;
        document.getElementById("serial_port").appendChild(opt);
    }
}

When my code block runs, I get an "Uncaught (in promise) hole" error. This code works fine on mac pc. My code was working on windows before. I think it is due to windows update. What should I do as a solution?

**Comment by PGIII** [comment]
Having same issue on 9.0.7 on my x86 Mac, buildDependenciesFromSource fixes the issue for me also. Apple Silicon Mac doesn't have the issue however but I suspect that's because it's building from source already
