### ISSUE TITLE
SerialPort.list() crashes Node on Windows while connecting and disconnecting devices.

### ISSUE THREAD

**Issue by gabrieleimotion** [serialport/node-serialport#2339]
## 💥  BUG

I've experienced the issue where I have a QRCode reader attached to the usb port of my machine, this device goes to stand-by after some time and it gets back when used. 
If I query for the device lists in this exact moment the nodejs process crashes without any unhandled exception on promise. 

How can I debug this? 

serialport version: ^9.2.4
node version: v8.17.0
npm version: v6.13.4

**Comment by GazHank** [comment]
Hi @gabrieleimotion are you able to confirm the node and SP versions you are using?

There was a recent change to the windows list function which improved stability, so if you are not already using the latest version then it might be worth a try

**Comment by gabrieleimotion** [comment]
@GazHank fair question, I updated my issue adding the version info :)

**Comment by GazHank** [comment]
Are you able to upgrade to v12+ of node since the prior versions are no longer supported

**Comment by gabrieleimotion** [comment]
I tried with v12.22.6 and still crashing without any error on serialport list.

**Comment by GazHank** [comment]
If you are still facing issues with a brother printer on the latest version then perhaps https://github.com/serialport/node-serialport/issues/2259 isn't fully resolved yet :-(

**Comment by gabrieleimotion** [comment]
Yes that's what I thought, but this happens sporadically and only on a combination of factors.
Is there useful a way I can get more info about the crash?
