### ISSUE TITLE
btc

### ISSUE THREAD

**Issue by helpmelorda** [serialport/node-serialport#2340]
## 📚 Documentation

(A clear and concise description of how the docs could be better, with links if possible)

### Have you read the [Contributing Guidelines on docs](https://github.com/serialport/node-serialport/blob/master/CONTRIBUTING.md#writing-documentation)?

(Write your answer here.)

**Comment by GazHank** [comment]
Sorry there doesn't appear to be any content in your proposal.  Could you please clarify?
