### ISSUE TITLE
version 9.0.0 dependce @serialport/bindings 9.2.8

### ISSUE THREAD

**Issue by FlyingNoob** [serialport/node-serialport#2364]
### SerialPort Version

9.0.0

### Node Version

16

### Electron Version

8.5.5

### Platform

Mac

### Architecture

x86

### What steps will reproduce the bug?

yarn add serialport@9.0.0

### What happens?

dependencey

@serialport/bindings 9.2.8

it should be dependence @serialport.bindings 9.0.0

### What should have happened?

integrated serialport 9.0.0

**Comment by GazHank** [comment]
I think we addressed this in https://github.com/serialport/node-serialport/pull/2276

Unfortunately that wasn't in place for 9.0.0 but it should work for recent version numbers
