### ISSUE TITLE
Doesn't build with Visual Studio Express 2013 for Windows Desktop

### ISSUE THREAD

**Issue by saffari** [serialport/node-serialport#248]
Asks for Visual Studio 2012, I installed the RTM version of Visual Studio 2013

![image](https://f.cloud.github.com/assets/1699228/1461855/98153d4c-44d1-11e3-88a6-19e64ccc6ae0.png)

**Comment by gautamkeshri** [comment]
Is there any alternative installation procedure without downloading Visual Studio Express 2013 (6.5GB) . I just need node to communicate with com port !
