### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by vgenev** [serialport/node-serialport#253]
I have following error:

<pre>
events.js:2817: Uncaught Error: Opening \\.\COM1: Access denied
</pre>

my program is: 

<pre>
var SerialPort = require("serialport").SerialPort;

var serialPort = new SerialPort('COM1',{baudrate: 9600}, true);

serialPort.on ('open', function () {
    console.log("Open");
    serialPort.write(0x05);
    serialPort.on ('data', function( data ) {
        console.log("data" + data.toString());
    });
});</pre>

What could be the reason?

I am trying to test the COM port working with cash register device.

**Comment by hernaneche** [comment]
Same here, win7x64, It solves restarting the PC
