### ISSUE TITLE
   After packing with electron, the running program reported an error that the module could not be found   

### ISSUE THREAD

**Issue by CaoXinHao** [serialport/node-serialport#2773]
### SerialPort Version

12.0.0

### Node Version

16.14.1

### Electron Version

28.2.1

### What steps will reproduce the bug?

  
My project environment: pnpm + vite5 + electron-builder24.13.3

After packaging with electron-builder, running an error occurred:
![image](https://github.com/serialport/node-serialport/assets/74801131/09488f2d-5809-4116-82b5-19d041a2ac94)
  
I tried to install the missing module and found that all the serialport dependencies were missing

 

### What happens?

  
The packaged exe cannot be opened

 

### What should have happened?

  
Normal open

**Comment by DaYao0704** [comment]
I had the same problem.Has the problem been solved now?

**Comment by CaoXinHao** [comment]
I have a problem with pnpm, which is going to have a problem in electron.  I can change yarn 

> 我有同样的问题。现在问题解决了吗？
