### ISSUE TITLE
multiple ports

### ISSUE THREAD

**Issue by ghost** [serialport/node-serialport#37]
i experienced problems while reading from multiple ports simultaneously.
up to 4 ports everything worked fine, when adding a fifth port reading is strange.

Data is only received after another port sent data as well.

Some quick code to test:

```
var sp = new SerialPort("/dev/tty.USA49Wfd1P1.1", global.serialOptions);
sp.on("data", datalistener);

var sp2 = new SerialPort("/dev/tty.USA49Wfd1P2.2", global.serialOptions);
sp2.on("data", datalistener);

var sp3 = new SerialPort("/dev/tty.USA49Wfd2P1.1", global.serialOptions);
sp3.on("data", datalistener);

var sp4 = new SerialPort("/dev/tty.USA49Wfd2P2.2", global.serialOptions);
sp4.on("data", datalistener);

var sp5 = new SerialPort("/dev/tty.USA49Wfd1P3.3", global.serialOptions);
sp5.on("data", datalistener);
```

Did anyone got similiar results or got an idea how to fix this? thank you.

**Comment by happyiphone** [comment]
Found the same problem on my system today. I migrated from lubuntu with 7 ports (controlling different pieces of equipment in an automation system) and then I moved to Windows 8.1 on an intel NUC, after the first attempts to fix my code I realized that if I have 3 port declarations everything works wonderfully, just by adding an extra port declaration the ports (all of them stop working). I have a machine ready to be tested (code and connections, the code will LOOK like it works but in fact it isn't I can see the result of the commands on the different equipment in real time (sound, tvs, etc.) if needed, just let me know and I'll provide access to it.
