### ISSUE TITLE
Intermittent crashes on Win7, exit code -1073741819

### ISSUE THREAD

**Issue by luffs** [serialport/node-serialport#74]
It hasn't failed to crash within 5-10 minutes yet, usually faster. No stack trace is printed, node just shuts down with the exit code -1073741819. When you google for it, you'll find that it's Windows code for Access Violation Error. ( 0xC0000005 in hex )

I've been working on a Node.JS module for the RFXtrx433, an USB device that lets you talk to home appliances on the 433.33Mhz frequency. I have no problem with crashes when I'm using the VB.NET code that comes with the device SDK.

See also: https://github.com/joeferner/node-serialport2/issues/8

Things I've tried:

Run as Administrator
Compatibility mode set to Windows XP / 98
Unplug the FTDI USB com port, and just use the com port on my motherboard

No luck, node still crashes within a couple of minutes.

Does it work without crashing for anyone else on Windows 7 64bit?

**Comment by Lange** [comment]
I just got this on Windows 10 64bit, node v6.9.1, serialport v4.0.7. No other errors were logged, the process just abruptly exited with this code. I can't be 100% sure that serialport is what caused this error, but given the presence of this issue, it seems likely.
